[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false
  style = "monokai"
  lineNumbers = false
  codeFences = true
  guessSyntax = true

[tableOfContents]
  startLevel = 2
  endLevel = 4
